### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raffaele-capasso**
As mentioned in #69, Users can choose how many copies want to print.

### CODE REVIEW

**Review by arcadius — APPROVED** [review]
Thanks @raffaele-capasso

**Comment by arcadius** [comment]
@raffaele-capasso , 

- I suppose there is going to be some code changes to propagate this parameter down to the native code?

- Did you manage to test this?

Thanks

**Comment by raffaele-capasso** [comment]
@arcadius 
_I suppose there is going to be some code changes to propagate this parameter down to the native code?_
Yes. I had to edit printer interface and the class that implement it.

_Did you manage to test this?_
Yes. It works very well both Android and iOS...

Thanks to you
Have a nice and "coding" day!

**Comment by arcadius** [comment]
Thank you very much @raffaele-capasso , most appreciated.

**Pull request merged**
